### ISSUE TITLE
Now x86 doesn't compile in new version

### ISSUE THREAD

**Issue by themronion** [roubachof/Sharpnado.Shadows#15] opened 2020-07-24 09:58 UTC
**Platform (please complete the following information):**
 - OS: Windows
 - Sdk vervion: latest
 - Xamarin.Forms: latest

**Describe the bug**
Now after you have added the x64 uwp dll in the new version - getting errors when compiling x86. It's a closed circuit :D Maybe try to reach out nuget support, maybe they know how to include both x64 and x86 dlls? 

**Exceptions (if applicable)**
Copy paste the exception and the stack trace
```
error MSB3270: There was a mismatch between the processor architecture of the project being build "x86" and the processor architecture of the reference "C:\Users\pluki_000\.nuget\packages\sharpnado.shadows\1.1.0\lib\uap10.0.16299\Sharpnado.Shadows.dll", "AMD64" (and the same for Sharpnado.Shadows.UWP.dll)
```

**Comment by roubachof** [comment] 2020-07-24 10:04
duplicate of #9

**Closed by roubachof** 2020-07-24 10:04 UTC
