### ISSUE TITLE
BackgroundColor Transparent isn't so transparent..

### ISSUE THREAD

**Issue by dpuckett** [roubachof/Sharpnado.Shadows#19] opened 2020-08-14 11:56 UTC
**Platform (please complete the following information):**
 - OS: [Android/Both]
 - Device: AndroidEmulator/OnePlus 6T
 - Sdk vervion: [Android SDK 29]
 - Xamarin.Forms: 4.6.0.1073

Applying a shadow to an item at the top of a stack layout. I then have a ListView immediately below it. 
The idea was to have the list when scrolling look like items are moving underneath the item at the top of the stack layout.

After applying a shadow, the background colour of the item to which the shadow is on top of runs until the end of the shadow.
So if something is to pass 'under' it, the effect is lost.

-Add StackLayout with a SearchBar, and then a ListView.
- Apply a white background to the SearchBar and a slightly darker background to the ListView
-Add items to the list so it scrolls
-Apply a shadow to the SearchBar and set BackgroundColor to Transparent
-Scroll screen and notice the darker background proceeds past the end of the shadow

`<sh:Shadows
                BackgroundColor="Transparent"
                Shades="{sh:SingleShade 
                            BlurRadius=3,
                            Offset='0,0',
                            Opacity=0.8,
                            Color=Black}">`

![Shadow Not Transparent](https://user-images.githubusercontent.com/5477570/90246546-c861c780-de2c-11ea-94fe-43afcd727555.png)
![image](https://user-images.githubusercontent.com/5477570/90246814-4e7e0e00-de2d-11ea-952d-73694174d6d3.png)

**Comment by roubachof** [comment] 2020-08-14 17:41
Mhmm sorry I don't understand. I don't know how you achieve this grey background under your search bar. Shadows on Android are just a intrinsic blur script applied to a rectangle...

**Comment by Jerome-Liger** [comment] 2020-09-11 16:44
I see what @dpuckett explained... because I got the same "problem".

When the shadow is added around any view, the "background" of the shadow in not transparent (or maybe it "take" a fixed size, not a "relative") and the collectionView elements are "cut" (and our designer says "it's uggly, need transparency" ;-) )

I don't know how are Shadows implemented, and I've tried to give it BackgroundColor="Transparent" and even in the Shade property Opacity=0.5, but nothing to workaround this :-(

I've made a zoom and explaination of @dpuckett image to better understand.
You can see that the item of the collectionview is "cut" (and we expected that the shadow were "relative" to the view, and transparent)

If you got a solution (and/or explaination), I take it !

![transparency](https://user-images.githubusercontent.com/39192143/92951505-be001100-f45e-11ea-91f9-5687112a8458.png)

**Comment by roubachof** [comment] 2020-09-11 17:09
I’m pretty sure this shadow is not coming from Shadows but from the search component itself... but if you have a reprise sample I can have a look

**Comment by Jerome-Liger** [comment] 2020-09-11 17:33
nop, I got the same without searchbar, but a simple ContentView with shadow, and a CollectionView.
But I think it's because shadows are not "relativelayout" around the view (cause the shadows are "taking space" around the view... I've been forced to set padding/spacing to 0 beetween my differents stacked shadows view)... so it can't be (by layout design) transparent ;-)
I'll try to make a simple repro.

**Comment by roubachof** [comment] 2020-09-11 17:48
Well it’s super weird cause I never saw à transparency issue before. Please share a repro sample 😁

**Comment by Jerome-Liger** [comment] 2020-09-11 18:50
Here's a repro sample, and the "bug" is not what I thought...
in fact, in my current project, I got "small" 4dp shadows... so I thought it was from a "transparency" or "relative layout" problem, but no, it's not that at all...
I made big shadows for repro, and the problem is well visible and explained in the image.

![Screenshot_20200911-202839](https://user-images.githubusercontent.com/39192143/92961520-aa10db00-f46f-11ea-8859-e47309d41d42.jpg)

Here the Repro sources :

[TransparentShadowsTest.zip](https://github.com/roubachof/Sharpnado.Shadows/files/5210991/TransparentShadowsTest.zip)

**Comment by roubachof** [comment] 2020-09-11 19:20
Perfect 👌 will have a look on Monday

**Comment by dpuckett** [comment] 2020-09-13 10:32
I managed to fix my original problem by understanding what the elements are actually doing, and it's not actually an issue when broken down.

The shadow is a control that is part of the stacklayout same as others, and to assume it would overlap the next item is wrong. It takes an amount of space where it displays a gradient, and then the next item in the layout is rendered. 

To get the overlaying effect you need to actually place the control with a shadow on top of the list control. You can do this easily with a grid, by setting both items to the same row number and Vertical options to Start. 
You then put a margin on the item underneath to match the height of the object on top.

**Comment by roubachof** [comment] 2020-09-17 09:20
So it seems this is a bug in XF but not a Shadows related issue:

![image](https://user-images.githubusercontent.com/596903/93451632-b82f8300-f8d7-11ea-9144-0ffff8dc3604.png)

**Comment by dpuckett** [comment] 2020-09-17 10:01
> So it seems this is a bug in XF but not a Shadows related issue:
> 
> ![image](https://user-images.githubusercontent.com/596903/93451632-b82f8300-f8d7-11ea-9144-0ffff8dc3604.png)
> 
> You can workaround this xf bug by setting Margin="0,-5" in your list view

This isn't a bug in either. Read my previous comment to find how to do this properly. I'll post some code later when I'm back to my desk.

**Comment by roubachof** [comment] 2020-09-17 10:21
mmh no, I stand my ground, there is a bug in XF :)

**Comment by dpuckett** [comment] 2020-09-17 11:18
This isn't a bug, look at your own code and think about what it is doing and you will see.
Just because the control says "Shadow" does not mean our determination of what a shadow should do is correct.

The element on the screen is just that, an element on the screen. It takes up space on a z index plain just the same as any other element.
You have a grid there, and have explicitly told each item in it what row to be displayed on, one under the other.

'<Shadow Grid.Row="0"....'

'<ListView Grid.Row="1"...'

Therefore the Listview WILL BE DISPLAYED BELOW THE SHADOW in terms of stacking.

What you need to do is layer items on top of each other in terms of z index.

Change ListView to be Grid.Row="0", then apply a margin to be the same height as the content view, 100, and you will see.

This. is. not. a. bug.

**Comment by roubachof** [comment] 2020-09-17 11:24
Mmmh sorry man but you're not talking about the same issue.
Here we are speaking about the 5dp space between ListView and ContentView inside a Grid with RowDefinition set to Auto :)

We are not speaking about Z-index issue, that you are resolving in a non-optimum way, instead of applying margin of the same height... You just have to position your custom Toolbar after the ListView declaration but still with a Row of 0:

```
Grid = '65,*'
    ListView Row = 1
    Shadow Row = 0 
        Toolbar 
```    

:)

**Comment by dpuckett** [comment] 2020-09-17 11:35
I am talking about the same problem. You are failing to realise that the Shadow control TAKES UP SPACE ON THE SAME PLAIN!
Just because it is a "shadow" does not mean it will not require space in order to be displayed.

The point you are attempting to make is that _because it's a shadow_ it shouldn't take any physical space and should be displayed over the top of anything else butted up to it.

That is wrong.

The control requires space on the screen in order to display the gradient colour. In your case this amount of space is "5dp".
Like you said before:

> Shadows on Android are just a intrinsic blur script applied to a rectangle...

That rectangle will consume physical space.

**Comment by roubachof** [comment] 2020-09-17 11:45
Look at the code I post above, I can recreate the same issue @Jerome-Liger is having *without* shadows, just with a `ContentView`.
So the issue from Jerome has nothing to do with shadows. 
Yours I have no idea, cause I didn't have a repro.
And no the rectangle will not consume physical space as you said cause positioning of blurred rectangle are made in the view canvas. So it won't push views around. 

                float x = source.GetX() + shadeInfo.OffsetX - MaxRadius;
                float y = source.GetY() + shadeInfo.OffsetY - MaxRadius;

                canvas.DrawBitmap(shadow, x, y, null);

You can verify this by setting the `BackgroundColor` of the XF Shadows view, you'll see it take only the same space as the content. Your diagnostic is seducing but in fact wrong.

**Comment by dpuckett** [comment] 2020-09-17 12:20
> Look at the code I post above, I can recreate the same issue @Jerome-Liger is having _without_ shadows, just with a `ContentView`.
> So the issue from Jerome has nothing to do with shadows.
> Yours I have no idea, cause I didn't have a repro.
> And no the rectangle will not consume physical space as you said cause positioning of blurred rectangle are made in the view canvas. So it won't push views around.
> 
> ```
>             float x = source.GetX() + shadeInfo.OffsetX - MaxRadius;
>             float y = source.GetY() + shadeInfo.OffsetY - MaxRadius;
> 
>             canvas.DrawBitmap(shadow, x, y, null);
> ```
> 
> You can verify this by setting the `BackgroundColor` of the XF Shadows view, you'll see it take only the same space as the content. Your diagnostic is seducing but in fact wrong.

Have you tried setting the RowSpacing on the grid.... sigh.

![image](https://user-images.githubusercontent.com/5477570/93469381-575c7680-f8e8-11ea-8832-936000cc8b39.png)

![image](https://user-images.githubusercontent.com/5477570/93469490-7b1fbc80-f8e8-11ea-81b5-68303465a53e.png)

**Comment by roubachof** [comment] 2020-09-17 12:24
Ahah i always forget about bloody row spacing. So all this mystery is over. Thank you for implicitly acknowledging your wrongs here 😂. I’m closing the issue

**Closed by roubachof** 2020-09-17 12:24 UTC

**Comment by Jerome-Liger** [comment] 2020-09-17 13:24
OMG... rowspacing... I often forgot it too :-D
Thanks for your invastigations

**Comment by roubachof** [comment] 2020-09-17 13:31
You can thank @dpuckett for this! I always create a implicit style and set all the Row and Column spaces to 0. There shouldn’t be a default value 😀
