### ISSUE TITLE
Shadow White Box

### ISSUE THREAD

**Issue by MRT-77** [roubachof/Sharpnado.Shadows#33] opened 2021-05-15 18:26 UTC
- OS: Windows10 20H2
 - Device: PC
 - Sdk vervion: UWP Target: 19041
 - Xamarin.Forms: 5.0.0.2012

I noticed a white box under the shadow and after disabling lines 113 and 136 in the `UWPShadowsController.cs`, the problem was fixed

![with-white-box](https://user-images.githubusercontent.com/40250976/118374071-6575aa80-b5cf-11eb-90ea-dfa709b95f60.png)

![without-white-box](https://user-images.githubusercontent.com/40250976/118374119-9fdf4780-b5cf-11eb-9c3e-cbb0583da3b5.png)

**Comment by MRT-77** [comment] 2021-05-16 00:20
Sorry, this trick wont work on every element.

**Comment by roubachof** [comment] 2021-05-18 07:32
duplicate of https://github.com/roubachof/Sharpnado.Shadows/issues/26

**Closed** 2021-05-28 08:47 UTC
Labels: duplicate
